project:
  type: website
  output-dir: docs

website:
  title: "BiodivPond"
  site-url: https://biodivpond.github.io
  repo-url: https://github.com/BiodivPond/
  favicon: Materials/Logos/biodivpond_logo_round.png
  navbar:
    logo: Materials/Logos/biodivpond_logo.png
    left:
      - href: about.qmd
        text: About
      - href: partners.qmd
        text: Partners
      - href: events.qmd
        text: Events
      - href: outcomes.qmd
        text: Outcomes
      - href: outreach.qmd
        text: Outreach
    right:
      - href: https://aopk.gov.cz/
        text: AOPK ƒåR

page-footer:
  left: "&copy; Copyright 2025, BiodivPond"
  right: "This page is built with ‚ù§üíöüê∏ and [Quarto](https://quarto.org/) by Jon√°≈° Gaigr."
  issue-url: https://github.com/BiodivPond/BiodivPond.github.io/issues
  repo-actions: [source, issue]

format:
  html:
    theme: cosmo
    toc: true
    title-block-banner: true
    title-block-logo: Materials/Logos/biodivpond_logo.png

extra-files:
  - styles.css
