project:
  type: website
  output-dir: docs

website:
  title: "BiodivPond"
  site-url: https://biodivpond.github.io
  repo-url: https://github.com/BiodivPond/
  favicon: Materials/Logos/biodivpond_logo_round.png

  navbar:
    logo: Materials/Logos/biodivpond_logo_round.png
    left:
      - href: about.qmd
        text: About
        
      - href: partners.qmd
        text: Partners
      
      - text: Events
        menu: 
          - href: workshop_2026.qmd
            text: International workshop 2026
          - href: workshop_2026.qmd
            text: International workshop 2027
          - href: natworkshops.qmd
            text: National workshops
          
      - href: outcomes.qmd
        text: Outcomes
      
      - text: Outreach
        menu: 
          - href: outreach.qmd
            text: Press release 2026
          - href: outreach.qmd
            text: Blog posts
          - href: outreach.qmd
            text: Meeting reports
          
    right:
      - href: https://aopk.gov.cz/web/en
        text: NCA CR
      - href: https://www.biodiversa.eu/
        text: Biodiversa+

  page-footer:
    left: "&copy; Copyright 2025, BiodivPond"
    right: "This page is built with ‚ù§üíöüê∏ and [Quarto](https://quarto.org/) by Jon√°≈° Gaigr."
    #issue-url: https://github.com/BiodivPond/BiodivPond.github.io/issues
    #repo-actions: [source, issue]

format:
  html:
    theme: cosmo
    toc: true
    title-block-banner: false
    title-block-logo: Materials/Logos/biodivpond_logo_round.png
    css: styles.css
